### ISSUE TITLE
Players getting kicked after trying to set a skin: Internal Exception: io.netty.handler.codec.DecoderException: The received string length is longer than maximum allowed (24 > 20)

### ISSUE THREAD

**Issue by BrainStone** [McLive/SkinsRestorerX#94]
### Describe the problem in a few short sentences

When trying to set a skin with `/skin <name>` on a SpongeForge-Server behind a Bungee, the player gets kicked with this exception on the SpongeForge Server:
https://gist.github.com/BrainStone/143c5d218d499ec2a31f5ecbf56a0740

### How can we reproduce the problem?

Run `/skin <name>` on latest SpongeForge server behind a bungee proxy (I'd recommend using Waterfall, as that has better (Sponge)Forge support)

### What version of SkinsRestorerX are you using?
13.5

### What is your Spigot/BungeeCord/Sponge version?
BungeeCord: git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178
SpongeForge: 1.12.2-2705-7.1.0-BETA-3438
Minecraft Forge: 14.23.4.2705

**Comment by BrainStone** [comment]
This also happens on Spigot!

Where I don't have ViaVersion installed!

Spigot: git-Spigot-2cf50f0-2b93d83

**Comment by BrainStone** [comment]
I found the issue I think:

```
> [00:38:30 ERROR]: Error occurred while enabling SkinsRestorer v13.5-SNAPSHOT (Is it up to date?)
org.bukkit.plugin.messaging.ChannelNameTooLongException: Attempted to send a Plugin Message to a channel that was too large. The maximum length a channel may be is 20 chars (attempted 24 - 'skinsrestorer:skinchange.
at org.bukkit.plugin.messaging.StandardMessenger.validateChannel(StandardMessenger.java:446) ~[server.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.plugin.messaging.StandardMessenger.registerOutgoingPluginChannel(StandardMessenger.java:179) ~[server.jar:git-Spigot-2cf50f0-2b93d83]
at skinsrestorer.bukkit.SkinsRestorer.onEnable(SkinsRestorer.java:98) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [server.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [server.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-2cf50f0-2b93d83]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```
